ALTER POLICY "allergens_tenant_isolation" ON "allergens" TO public USING (current_setting('app.is_platform_admin', true) = 'true' OR "allergens"."establishment_id"::text = current_setting('app.current_establishment_id', true));--> statement-breakpoint
ALTER POLICY "cancellation_policies_tenant_isolation" ON "cancellation_policies" TO public USING (current_setting('app.is_platform_admin', true) = 'true' OR "cancellation_policies"."establishment_id"::text = current_setting('app.current_establishment_id', true));--> statement-breakpoint
ALTER POLICY "categories_tenant_isolation" ON "categories" TO public USING (current_setting('app.is_platform_admin', true) = 'true' OR "categories"."establishment_id"::text = current_setting('app.current_establishment_id', true));--> statement-breakpoint
ALTER POLICY "clients_tenant_isolation" ON "clients" TO public USING (current_setting('app.is_platform_admin', true) = 'true' OR "clients"."establishment_id"::text = current_setting('app.current_establishment_id', true));--> statement-breakpoint
ALTER POLICY "inter_entity_invoices_tenant_isolation" ON "inter_entity_invoices" TO public USING (current_setting('app.is_platform_admin', true) = 'true' OR "inter_entity_invoices"."establishment_id"::text = current_setting('app.current_establishment_id', true));--> statement-breakpoint
ALTER POLICY "legal_entities_tenant_isolation" ON "legal_entities" TO public USING (current_setting('app.is_platform_admin', true) = 'true' OR "legal_entities"."establishment_id"::text = current_setting('app.current_establishment_id', true));--> statement-breakpoint
ALTER POLICY "notifications_tenant_isolation" ON "notifications" TO public USING (current_setting('app.is_platform_admin', true) = 'true' OR "notifications"."establishment_id"::text = current_setting('app.current_establishment_id', true));--> statement-breakpoint
ALTER POLICY "orders_tenant_isolation" ON "orders" TO public USING (current_setting('app.is_platform_admin', true) = 'true' OR "orders"."establishment_id"::text = current_setting('app.current_establishment_id', true));--> statement-breakpoint
ALTER POLICY "production_lots_tenant_isolation" ON "production_lots" TO public USING (current_setting('app.is_platform_admin', true) = 'true' OR "production_lots"."establishment_id"::text = current_setting('app.current_establishment_id', true));--> statement-breakpoint
ALTER POLICY "products_tenant_isolation" ON "products" TO public USING (current_setting('app.is_platform_admin', true) = 'true' OR "products"."establishment_id"::text = current_setting('app.current_establishment_id', true));--> statement-breakpoint
ALTER POLICY "staff_members_tenant_isolation" ON "staff_members" TO public USING (current_setting('app.is_platform_admin', true) = 'true' OR "staff_members"."establishment_id"::text = current_setting('app.current_establishment_id', true));